_wandb:
    value:
        cli_version: 0.22.3
        e:
            d6vmjfwi7xxjaisryhevjk0jf0ll88fk:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: run_cacla.py
                codePathLocal: run_cacla.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "97196142592"
                email: hyloradotcom@gmail.com
                executable: /opt/anaconda3/bin/python
                host: NAT-INSIDE-192-168-215-111.rrz.uni-hamburg.de.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/hyloradotcom/Documents/ERAMSUS/KPISseminar/CACLA2/run_cacla.py
                python: CPython 3.13.5
                root: /Users/hyloradotcom/Documents/ERAMSUS/KPISseminar/CACLA2
                startedAt: "2025-11-05T15:59:35.128085Z"
                writerId: d6vmjfwi7xxjaisryhevjk0jf0ll88fk
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 13
            "4": 3.13.5
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
