_wandb:
    value:
        cli_version: 0.22.2
        e:
            ouxc36l0k4u7k3ow8982xslr7e91f800:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "60667936768"
                email: hyloradotcom@gmail.com
                executable: /opt/anaconda3/envs/cleanrl_env/bin/python
                host: NAT-INSIDE-192-168-210-70.rrz.uni-hamburg.de.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/hyloradotcom/Desktop/KPISseminar/CACLA2/main.py
                python: CPython 3.10.19
                root: /Users/hyloradotcom/Desktop/KPISseminar/CACLA2
                startedAt: "2025-10-22T16:04:15.288126Z"
                writerId: ouxc36l0k4u7k3ow8982xslr7e91f800
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.19
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
learning_rate:
    value: 0.01
