_wandb:
    value:
        cli_version: 0.22.3
        code_path: code/sac_pendulum_cleanrl.py
        e:
            0da9khygb6kltw6ulgr6tdgo6uvopr75:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: sac_pendulum_cleanrl.py
                codePathLocal: sac_pendulum_cleanrl.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "97373237248"
                email: hyloradotcom@gmail.com
                executable: /opt/anaconda3/bin/python
                host: NAT-INSIDE-192-168-215-111.rrz.uni-hamburg.de.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/hyloradotcom/Documents/ERAMSUS/KPISseminar/CACLA2/sac_pendulum_cleanrl.py
                python: CPython 3.13.5
                root: /Users/hyloradotcom/Documents/ERAMSUS/KPISseminar/CACLA2
                startedAt: "2025-11-05T16:48:44.583989Z"
                writerId: 0da9khygb6kltw6ulgr6tdgo6uvopr75
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.13.5
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
alpha:
    value: 0.2
autotune:
    value: true
batch_size:
    value: 256
buffer_size:
    value: 1000000
capture_video:
    value: false
cuda:
    value: true
env_id:
    value: Pendulum-v1
exp_name:
    value: sac-run
gamma:
    value: 0.99
learning_starts:
    value: 5000
noise_clip:
    value: 0.5
policy_frequency:
    value: 2
policy_lr:
    value: 0.0003
q_lr:
    value: 0.001
seed:
    value: 1
target_network_frequency:
    value: 1
tau:
    value: 0.005
torch_deterministic:
    value: true
total_timesteps:
    value: 200000
track:
    value: true
wandb_entity:
    value: null
wandb_project_name:
    value: cacla-vs-cleanrl-benchmark
